log_level: INFO

nut:
  ups: "ups@localhost"
  username: "upsmon"
  password: "haven"

poll_interval: 12       # How often to poll (in seconds)

wake_on:
  restore_delay_sec: 30       # Delay after power is restored before sending WOL
  min_battery_percent: 82     # Wait until battery is charged to this level
  client_timeout_sec: 600   # If client doesn't respond after WOL, log error
  reattempt_delay: 30

clients:
  - name: test1
    host: prox-server.home
    mac: 38:f7:cd:c5:78:2b           # Will resolve MAC using ARP
  - name: test2
    host: 192.168.10.41
    mac: auto        # Will resolve MAC using ARP
  - name: x1
    host: 192.168.10.224
    mac: 58:47:ca:7c:9b:d2           # Will resolve MAC using ARP